openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:8090
tags:
  - name: tasks
    description: Task related enpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
